In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[9,8,0],[1,4,3]])

In [3]:
A

array([[1, 2, 3],
       [9, 8, 0],
       [1, 4, 3]])

In [17]:
A.ravel()

array([1, 2, 3, 9, 8, 0, 1, 4, 3])

In [18]:
A.dtype

dtype('int32')

In [4]:
A.shape

(3, 3)

In [7]:
A[0:3,:]

array([[1, 2, 3],
       [9, 8, 0],
       [1, 4, 3]])

In [9]:
A[0:2,0:2]

array([[1, 2],
       [9, 8]])

In [10]:
A[0:3,0:2]

array([[1, 2],
       [9, 8],
       [1, 4]])

In [11]:
A[1:3,2:3]

array([[0],
       [3]])

In [12]:
A[0:3,1:2]

array([[2],
       [8],
       [4]])

In [13]:
A[1:2,0:3]

array([[9, 8, 0]])